### ISSUE TITLE
Can't create java app form Quickstart template

### ISSUE THREAD

**Issue by hamfors** [fabric8io/fabric8#6118]
Hi,
I use fabric8 with vigrant and I can create an node app from the Quickstart templates. The pipeline works perfectly. But when I try the java examples (war,main-class etc) it fails with this error message:

[INFO] Copying files to /home/jenkins/workspace/workspace/fifi/target/docker/172.30.239.254/80/fabric8/fifi/1.0.1/build/maven

[INFO] Building tar: /home/jenkins/workspace/workspace/fifi/target/docker/172.30.239.254/80/fabric8/fifi/1.0.1/tmp/docker-build.tar

[INFO] DOCKER> docker-build.tar: Created [172.30.239.254:80/fabric8/fifi:1.0.1] in 120 milliseconds

[INFO] DOCKER> [172.30.239.254:80/fabric8/fifi:1.0.1]: Built image f38f92b6609e

[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 32.949 s

[INFO] Finished at: 2016-06-30T13:29:29+00:00

sh-4.2# exit

exit

[INFO] Final Memory: 48M/406M

[INFO] ------------------------------------------------------------------------

[Pipeline] readMavenPom

[Pipeline] tagImage

Tagging image:gavagai/fifi:1.0.1 with tag:1.0.1.

[Pipeline] }

[Pipeline] // withPod

[Pipeline] }

[Pipeline] // node

[Pipeline] End of Pipeline

Found Elasticsearch server, sending:{"timestamp":"2016-06-30T13:28:14.744+0000","build_number":1,"app":"fifi","build_result":"FAILURE","start_time":"2016-06-30T13:28:14.746+0000","duration":0,"env_vars":{"BUILD_DISPLAY_NAME":"#1","BUILD_ID":"1","BUILD_NUMBER":"1","BUILD_TAG":"jenkins-fifi-1","CLASSPATH":"","HUDSON_HOME":"/var/jenkins_home","HUDSON_SERVER_COOKIE":"b28e82c171d446aa","JENKINS_HOME":"/var/jenkins_home","JENKINS_SERVER_COOKIE":"b28e82c171d446aa","JOB_NAME":"fifi"},"build_url":"job/fifi/1/","causes":[{"short_description":"Started by user anonymous","user_name":"anonymous"}]}

Event created

io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/images/gavagai/fifi:1.0.1/tag?tag=1.0.1&force=false&repo=172.30.239.254:80/gavagai/fifi. Status:404. Message: Not Found. Body: could not find image: no such id: gavagai/fifi:1.0.1

at io.fabric8.docker.client.impl.OperationSupport.requestFailure(OperationSupport.java:255)

at io.fabric8.docker.client.impl.OperationSupport.assertResponseCodes(OperationSupport.java:239)

at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:191)

at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:88)

at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:33)

at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:50)

at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:41)

at hudson.remoting.UserRequest.perform(UserRequest.java:121)

at hudson.remoting.UserRequest.perform(UserRequest.java:49)

at hudson.remoting.Request$2.run(Request.java:326)

at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at hudson.remoting.Engine$1$1.run(Engine.java:69)

at java.lang.Thread.run(Thread.java:745)

at ......remote call to 255e6cded08(Native Method)

at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)

at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)

at hudson.remoting.Channel.call(Channel.java:781)

at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:41)

at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:28)

at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)

at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:137)

at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)

at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)

at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)

at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:298)

at io.fabric8.kubernetes.pipeline.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:33)

at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:297)

at mavenCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/mavenCanaryRelease.groovy:22)

at WorkflowScript.run(WorkflowScript:46)

at io.fabric8.kubernetes.pipeline.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:123)

at ___cps.transform___(Native Method)

at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)

at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)

at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)

at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)

at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)

at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)

at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)

at com.cloudbees.groovy.cps.Next.step(Next.java:58)

at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)

at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)

at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)

at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

Finished: FAILURE

**Comment by AaoGITKarein** [comment]
Hi

I am facing the same issue.

Found Elasticsearch server, sending:{"timestamp":"2016-07-05T06:47:34.304+0000","build_number":6,"app":"my-cool-first-project","build_result":"FAILURE","start_time":"2016-07-05T06:47:34.309+0000","duration":0,"env_vars":{"BUILD_DISPLAY_NAME":"#6","BUILD_ID":"6","BUILD_NUMBER":"6","BUILD_TAG":"jenkins-my-cool-first-project-6","CLASSPATH":"","HUDSON_HOME":"/var/jenkins_home","HUDSON_SERVER_COOKIE":"317a5bee30207125","JENKINS_HOME":"/var/jenkins_home","JENKINS_SERVER_COOKIE":"317a5bee30207125","JOB_NAME":"my-cool-first-project"},"build_url":"job/my-cool-first-project/6/","causes":[{"short_description":"Started by user anonymous","user_name":"anonymous"}]}
Event created
io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/images/example/my-cool-first-project:1.0.6/tag?tag=1.0.6&force=false&repo=172.30.99.107:80/example/my-cool-first-project. Status:404. Message: Not Found. Body: could not find image: no such id: example/my-cool-first-project:1.0.6

	at io.fabric8.docker.client.impl.OperationSupport.requestFailure(OperationSupport.java:255)
	at io.fabric8.docker.client.impl.OperationSupport.assertResponseCodes(OperationSupport.java:239)
	at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:191)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:88)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:33)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:50)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:41)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to 530bd67e23d0(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:41)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:28)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:137)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:298)
	at io.fabric8.kubernetes.pipeline.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:297)
	at mavenCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/mavenCanaryRelease.groovy:22)
	at WorkflowScript.run(WorkflowScript:46)
	at io.fabric8.kubernetes.pipeline.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:123)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor298.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor301.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)
	at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

**Comment by jstrachan** [comment]
this looks to be a duplicate of https://github.com/fabric8io/fabric8/issues/6131 - we'll hopefully have this fixed really soon; looks like a regression in the docker registry handling / maven plugin...

**Comment by rawlingsj** [comment]
yeah this is a duplicate of https://github.com/fabric8io/fabric8/issues/6131 which has now been fixed.  There's a workaround detailed in the above issue comments that can be used until the next release which should be tomorrow.  I'll leave this open till then so we can confirm its fixed.

**Comment by rawlingsj** [comment]
this is fixed now with the latest release

**Comment by LarsMilland** [comment]
Hi

It does not appear so that the issue is completely solved. I am running a MavenCanaryRelease Jenkins pipeline build of the release 2.2.219 of the jenkins-docker build setup of fabric8 on a multiserver cluster based setup of OpenShift 1.2.0, and are still seeing the same problems. That the push/tagging of the Docker images are not working, so builds stops when it tries to complete the pipeline step of placing the built Docker images to the fabric8 provided Docker repository as I understand it.

`[INFO] Copying files to /opt/jenkins/workspace/workspace/makro/target/docker/172.30.36.155/80/example/makro/1.0.1/build/maven
[INFO] Building tar: /opt/jenkins/workspace/workspace/makro/target/docker/172.30.36.155/80/example/makro/1.0.1/tmp/docker-build.tar
[INFO] DOCKER> docker-build.tar: Created [172.30.36.155:80/example/makro:1.0.1] in 5 seconds 
sh-4.2# exit
exit
[INFO] DOCKER> [172.30.36.155:80/example/makro:1.0.1]: Built image fd4a5b91d825
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.830 s
[INFO] Finished at: 2016-08-04T10:03:48+00:00
[INFO] Final Memory: 53M/573M
[INFO] ------------------------------------------------------------------------
[Pipeline] tagImage
Tagging image:example/makro:1.0.1 with tag:1.0.1.
[Pipeline] }
[Pipeline] // withPod
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace
io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/images/example/makro:1.0.1/tag?tag=1.0.1&force=false&repo=172.30.36.155:80/example/makro. Status:404. Message: Not Found. Body: could not find image: no such id: example/makro:1.0.1

	at io.fabric8.docker.client.impl.OperationSupport.requestFailure(OperationSupport.java:255)
	at io.fabric8.docker.client.impl.OperationSupport.assertResponseCodes(OperationSupport.java:239)
	at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:191)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:88)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:33)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:50)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:41)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to d855f2905ec3d(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:41)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:28)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:137)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:298)
	at io.fabric8.kubernetes.pipeline.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:297)
	at mavenCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/mavenCanaryRelease.groovy:24)
	at WorkflowScript.run(WorkflowScript:55)`

Best regards
Lars Milland

**Comment by KurtStam** [comment]
I can confirm seeing this. --K

**Comment by rawlingsj** [comment]
I think something recent has changed which means this is happening again.  We should be able to switch the pipelines to use the fabric8-maven-plugin 3.x as all the quickstarts should be ported by now.

Will look at fixing in the next day.

**Comment by BoriszhangSec** [comment]
i have same issue
[Pipeline] End of Pipeline

io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/images/example/javaapp:1.0.1/tag?tag=1.0.1&force=false&repo=10.96.160.15:80/example/javaapp. Status:404. Message: Not Found. Body: {"message":"no such id: example/javaapp:1.0.1"}

**Comment by amb-it-ion** [comment]
+1

**Comment by rawlingsj** [comment]
@amb-it-ion which quickstart are you using?  I wonder if there's still one that hasn't been migrated to the new f-m-p 3.x.

**Comment by amb-it-ion** [comment]
You are right, I used an old archetype following [this](https://fabric8.io/guide/quickstarts/archetypes.html) guide - maybe this should be updated to always use the latest?

Now I am stuck with [this](https://github.com/fabric8io/fabric8-maven-plugin/issues/634) using io.fabric8.funktion.starter:starter-parent-java:1.0.34 from the archetype funktion-java-example-archetype:2.2.185. Is there an open issue for this? I am a little lost, just entered the fabric8 universe.

**Comment by jangor** [comment]
@rawlingsj i have this issue with the fabric8 console wizzard **create app** where "Product Type" is "Java Web Application (WAR)"

information related
- gofabric8 version is **0.4.112**
- gofabric8 *windows-amd64* is locally installed on windows 10 and Hyper-V

**Comment by jstrachan** [comment]
@amb-it-ion looks like those issues are fixed & should be in the new versions of the quickstarts soon
