### ISSUE TITLE
CI/CD issues (Build Failures) with sample projects from fabric8 console

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#6390]
Recently (after I rebuilt minikube with GO 1.7.1 on Sierra) I have not been able to create any sample Apps and have these  build successfully. These previously build ok before I upgraded to Sierra.

From the fabric8 console.  I started with the GO example from the main Apps page. All looked ok until:

Tagging image:mygo1 with tag:0.

[Pipeline] }

[Pipeline] // node

[Pipeline] End of Pipeline

Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace

io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.

at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:85)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:68)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:64)

at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:81)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)

at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:431)

at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)

at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)

at performCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/performCanaryRelease.groovy:23)

at WorkflowScript.run(WorkflowScript:16)

at ___cps.transform___(Native Method)

at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:74)

at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)

at com.cloudbees.groovy.cps.Next.step(Next.java:58)

at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)

at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)

at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)

at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

Caused by: java.net.MalformedURLException: no protocol: kubernetes.default/

at java.net.URL.<init>(URL.java:593)

at java.net.URL.<init>(URL.java:490)

at java.net.URL.<init>(URL.java:439)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:82)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:68)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:64)

at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:81)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)

at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:431)

at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)

at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)

Then I ran Elastic Search but this won't start owing to:

Unable to mount volumes for pod "elasticsearch-2025438883-arkqf_default(8e068757-848c-11e6-8e32-dac6c5ade330)": timeout expired waiting for volumes to attach/mount for pod "elasticsearch-2025438883-arkqf"/"default". list of unattached/unmounted volumes=[data]

Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "elasticsearch-2025438883-arkqf"/"default". list of unattached/unmounted volumes=[data]

I then tried the .Net sample App and the Build failed with:

Successfully built 4096663861e1

[Pipeline] tagImage

Tagging image:mynet1 with tag:0.

[Pipeline] }

[Pipeline] // node

[Pipeline] End of Pipeline

Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace

io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.

at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:85)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:68)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:64)

at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:81)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)

at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:431)

at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)

at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)

at performCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/performCanaryRelease.groovy:23)

at WorkflowScript.run(WorkflowScript:16)

at ___cps.transform___(Native Method)

at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:74)

at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)

at com.cloudbees.groovy.cps.Next.step(Next.java:58)

at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)

at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)

at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)

at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

Caused by: java.net.MalformedURLException: no protocol: kubernetes.default/

at java.net.URL.<init>(URL.java:593)

at java.net.URL.<init>(URL.java:490)

at java.net.URL.<init>(URL.java:439)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:82)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:68)

at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:64)

at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:81)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)

at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:431)

at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)

at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)

... 24 more

Finished: FAILURE

**Comment by enxebre** [comment]
Same here,
first having elasticsearch connection issue so I deploy "loggin" app and then I have
```
Event created
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:85)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:68)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:64)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:81)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)
	at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:431)
	at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at mavenCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/mavenCanaryRelease.groovy:17)
	at WorkflowScript.run(WorkflowScript:42)
	at io.fabric8.kubernetes.pipeline.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:123)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:74)
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: no protocol: kubernetes.default/
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:82)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:68)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:64)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:81)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)
	at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:431)
	at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	... 24 more
Finished: FAILURE
```

At the end of the jenkins build for "Microservice" sample.

**Comment by rawlingsj** [comment]
ditto - I can reproduce it on AWS kubernetes 1.4, not sure what the problem is yet as the env var used definitely doesn't have that trailing /.  

still investigating...

**Comment by enxebre** [comment]
just FYI I'm on  kube v1.3.7

**Comment by rawlingsj** [comment]
Ah thanks @enxebre I was just about to try that.  Ok I'm trying the previously tagged version of fabric8 jenkins.

**Comment by rawlingsj** [comment]
Not sure yet why it's working on some installs but this is caused because KUBERNETES_MASTER env var needs `https` prefix, i.e. `https://kubernetes.default`

Until we get the fix released we can edit the jenkins deployment and update the KUBERNETES_MASTER env var:

```
kubectl edit deployment jenkins
```
and check the env var to match this https://github.com/fabric8io/fabric8-devops/pull/592/commits/be0664e8d5951056b1cca80f576d0a44c5fa3fb9

**Comment by enxebre** [comment]
cool @rawlingsj thanks for being so responsive

**Comment by rawlingsj** [comment]
no problem, sorry about the issue.  we're just fixing up a quickstart and then we'll kick off another release so should all be sorted in a few hours.

**Comment by enxebre** [comment]
@rawlingsj after editing jenkins build still failing due to:
```
Pushing image:10.3.0.253:80/default/go-sample to docker registry.
The push refers to a repository [10.3.0.253:80/default/go-sample]
ERROR: unable to ping registry endpoint https://10.3.0.253:80/v0/
v2 ping attempt failed with error: Get https://10.3.0.253:80/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.3.0.253:80/v1/_ping: tls: oversized record received with length 20527
```

curling to HTTP://10.3.0.253:80/v2/ from inside the kube cluster gives a 200

**Comment by rawlingsj** [comment]
@enxebre I'm pretty sure that's down to not having an insecure registry flag on the docker daemon options.  GKE and stackpointcloud do this OOTB but if you have your own installation then you'll need to update the docker config on each node to allow the insecure registry https://docs.docker.com/registry/insecure/#/deploying-a-plain-http-registry

If you use the kubernetes ansible scripts to install then there's a helpful env var to set before running the playbook `export KUBE_ENABLE_INSECURE_REGISTRY=true`  which is used https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/config-default.sh#L118

If you're doing things manually the you'll need to update the docker config on each node and add 
`--insecure-registry 10.0.0.0/8` then restart the docker service - note this will recreate your pods.

Hopefully that helps

**Comment by enxebre** [comment]
@rawlingsj yeah that was my first thought I was just expecting fabric8 to somehow warning me on the ui, or see something about that step on the docs.
I finally get green build. I'll leave this here for the record so it can help others and maybe myself or someone else can create a PR to improve the docs
Thanks again

* kubectl create --validate=false -f https://repo1.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.178/console-kubernetes-2.2.178-kubernetes.json

* gofabric8 deploy -y

* Run Logging

* Change Elasticsearch volume if your underlying infra does not support pvc

* kubectl edit deployment jenkins
  name: "KUBERNETES_MASTER"
  value: "https://kubernetes.default"

* Change docker daemon to --insecure-registry 10.0.0.0/8

**Comment by rawlingsj** [comment]
@enxebre you're right our docs could be clearer, we have something on the AWS ones: http://fabric8.io/guide/getStarted/aws.html#2-kubernetes-ansible-scripts but we can add clearer notes under other install guides.

Also we want to add a validator pod that starts once the initial deploy is finished that checks a docker push / push from the registry

https://github.com/fabric8io/fabric8/issues/6299

**Comment by enxebre** [comment]
@rajdavies just another note here as I'm using CNI network I had to edit the nginx deployment in order to access to my fabric8 services as the host ports won't work.
See:
https://github.com/kubernetes/kubernetes/issues/23920
https://github.com/kubernetes/kubernetes/issues/31307 
https://github.com/containernetworking/cni/issues/46
